GO

INSERT Employee ([Fname], [Minit], [Lname], [Ssn], [Bdate], [Address], [Sex], [Salary], [Super_ssn], [Dno])
VALUES
('Jackie', 'S', 'Buna', 001, '2004-01-16', 'Rizal Park', 'F', 10, 001, 001),
('loren', 'J', 'Jackie', 002, '2003-06-12', 'Mars', 'F',10, 001, 001),
('Rio', 'E', 'Espaldon', 003, '2002-09-20', 'Zoo', 'M', 10, 001, 001);
go

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
LEFT JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT. Mgr_ssn

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
RIGHT JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT. Mgr_ssn

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT. Mgr_ssn

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
CROSS JOIN DEPARTMENT

UPDATE EMPLOYEE
SET Fname = 'Cabilbigan'
WHERE Ssn=003
