CREATE TABLE [dbo].[DEPENDENT]
(
	[Essn] CHAR(9) NOT NULL, 
    [Dependent_name] VARCHAR(15) NOT NULL, 
    [Sex] CHAR(1),
    [Bdate] DATETIME, 
    [Relationship] VARCHAR(8),
   
   CONSTRAINT [PK_DEPENDENT_Essn, PK_DEPENDENT_name] PRIMARY KEY (Essn, Dependent_name),
   CONSTRAINT [FK_DEPENDENT_Ssn] FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn)
);

GO
CREATE NONCLUSTERED INDEX[IX_DEPENDENT_Sex] ON [DEPENDENT] ([Sex] ASC)
