CREATE TABLE [dbo].[DEPT_LOCATIONS]
(
	[Dnumber] INT NOT NULL, 
    [Dlocation] VARCHAR(15) NOT NULL ,
	CONSTRAINT [PK_Dlocation] PRIMARY KEY (Dnumber, Dlocation),
	CONSTRAINT [FX_Dnumber] FOREIGN KEY(Dnumber)  REFERENCES DEPARTMENT(Dnumber) 

);
GO

CREATE NONCLUSTERED INDEX [IX_DEPT.LOCATION_LOCATION] ON [DEPT_LOCATIONS] ([Dlocation] ASC)
